/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppHeading: typeof import('./src/components/AppHeading.vue')['default']
    AppToggleBtn: typeof import('./src/components/AppToggleBtn.vue')['default']
    CheckOut: typeof import('./src/components/CheckOut.vue')['default']
    CheckOutDetails: typeof import('./src/components/CheckOutDetails.vue')['default']
    Descreptions: typeof import('./src/components/Descreptions.vue')['default']
    Final: typeof import('./src/components/Final.vue')['default']
    FormInputs: typeof import('./src/components/FormInputs.vue')['default']
    GameExp: typeof import('./src/components/GameExp.vue')['default']
    GameExpContent: typeof import('./src/components/GameExpContent.vue')['default']
    OfferItem: typeof import('./src/components/OfferItem.vue')['default']
    Plan: typeof import('./src/components/Plan.vue')['default']
    PlanContent: typeof import('./src/components/PlanContent.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Steps: typeof import('./src/components/Steps.vue')['default']
    StepsContent: typeof import('./src/components/StepsContent.vue')['default']
  }
}
